<!-- src/lib/components/Blog.svelte -->
<script lang="ts">
    export let title: string = "Untitled";
    export let author: string = "Unknown";
    export let date: string = "";
    export let contentHtml: string = "";
    export let rawText: string = "";

    // Calculate word count and read time
    $: wordCount = rawText.trim().split(/\s+/).length;
    // Avg reading speed is ~150 wpm
    $: readTime = Math.ceil(wordCount / 150); 
    // Format date to a more readable form if it's in ISO format
    $: formattedDate = date ? new Date(date).toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    }) : "";
</script>

<article class="blog-container">
    <header class="blog-header markdown-body">
        <h1 class="name">{title}</h1>
        <div class="metadata">
            <span>[ Author: {author} ]</span>
            {#if date}<span>[ Date: {formattedDate} ]</span>{/if}
            <span>[ {wordCount} words | {readTime} min read ]</span>
        </div>
    </header>

    <!-- Render the main parsed markdown content here -->
    <div class="markdown-content">
        {@html contentHtml}
    </div>
</article>

<style>

    /* Remove default borders from headings and horizontal rules */
    :global(.markdown-body h1),
    :global(.markdown-body h2),
    :global(.markdown-body h3),
    :global(.markdown-body hr) {
        border-bottom: none !important;
        padding-bottom: 0 !important;
        margin-bottom: 0.5rem; /* Adjust spacing as needed without the line */
    }

    /* Completely hide the horizontal rule generated by markdown frontmatter */
    :global(.markdown-body hr) {
        display: none !important;
    }

    .blog-container {
        width: 100%;
        /* max-width: 800px; */
        margin: 0 auto;
        padding: 0 1rem;
    }
    .blog-container {
        width: 100%;
        /* max-width: 800px; */
        margin: 0 auto;
        padding: 0 1rem;
    }

    .blog-header {
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
    }

    .metadata {
        color: var(--white);
        font-size: calc(0.7em);
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
        margin-top: 1rem;
        word-break: break-word;
        overflow-wrap: break-word;
    }
    .name {
        font-family: 'Press Start 2P', sans-serif;
        margin-top: 5vh;
        color: var(--yellow) !important;
        font-size: calc(var(--title-size) * 0.8);
    }
    
</style>